table daysmart_contacts
	lineageTag: 9e1dd659-85cf-4f06-a98f-65df13385bf3

	column Customer_ID
		dataType: string
		lineageTag: e0df07aa-c749-482d-98d8-29c7ba389c99
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Full_Name
		dataType: string
		lineageTag: 943086eb-2512-4d82-9879-9ff79df63d79
		summarizeBy: none
		sourceColumn: Full_Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 1c7813d8-06f7-45a3-989d-5a9366176959
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: b9be87cc-9ef6-48ee-bed0-1f03555e783e
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Last_Appointment_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 74173f4c-e5cd-4cdb-9f75-8728312f90f6
		summarizeBy: none
		sourceColumn: Last_Appointment_Date

		variation Variation
			isDefault
			relationship: afddeb43-edf9-42dd-8a8c-546c2b3b780d
			defaultHierarchy: LocalDateTable_d0ea65f0-0f6f-4967-b43f-858e3f51e155.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Primary_Service
		dataType: string
		lineageTag: 51732e12-1385-4d2f-8c90-7dfb86663501
		summarizeBy: none
		sourceColumn: Primary_Service

		annotation SummarizationSetBy = Automatic

	column Assigned_Staff
		dataType: string
		lineageTag: 01f16899-261c-4e9a-a7b9-7057fc2e3492
		summarizeBy: none
		sourceColumn: Assigned_Staff

		annotation SummarizationSetBy = Automatic

	column Total_Appointments
		dataType: int64
		formatString: 0
		lineageTag: 98e3b141-3dd4-48f2-a4f3-ff820a954d2d
		summarizeBy: sum
		sourceColumn: Total_Appointments

		annotation SummarizationSetBy = Automatic

	column No_Shows
		dataType: int64
		formatString: 0
		lineageTag: 45c6feef-a2e6-48c1-abff-029401ba5a18
		summarizeBy: sum
		sourceColumn: No_Shows

		annotation SummarizationSetBy = Automatic

	column Total_Spent_USD
		dataType: double
		lineageTag: a1d8f312-12a4-4fae-88e3-82b0bc5a9651
		summarizeBy: sum
		sourceColumn: Total_Spent_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Loyalty_Points
		dataType: int64
		formatString: 0
		lineageTag: 11e09f29-c3a4-4f52-bcf5-4586eca5e1b6
		summarizeBy: sum
		sourceColumn: Loyalty_Points

		annotation SummarizationSetBy = Automatic

	column SMS_Opt_In
		dataType: string
		lineageTag: 8c7b1849-1c27-412f-b5b1-2b5b12d4cfc2
		summarizeBy: none
		sourceColumn: SMS_Opt_In

		annotation SummarizationSetBy = Automatic

	column Email_Opt_In
		dataType: string
		lineageTag: 21324dd3-27b0-43a2-95b4-7234b8a5cc32
		summarizeBy: none
		sourceColumn: Email_Opt_In

		annotation SummarizationSetBy = Automatic

	column Next_Appointment_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4a93b88-319b-430a-b786-360d468cd987
		summarizeBy: none
		sourceColumn: Next_Appointment_Date

		variation Variation
			isDefault
			relationship: a446e6c3-a4e4-4727-8a68-6f9b4d0ddd11
			defaultHierarchy: LocalDateTable_84ae36b1-b9dd-4088-9ea7-a18c8c160390.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Notes
		dataType: string
		lineageTag: 7fbda75c-6f5a-4e10-8af8-764eb4e64932
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Source_System
		dataType: string
		lineageTag: e7b1373c-dd7f-4a3e-bb98-5cdda2d5aefc
		summarizeBy: none
		sourceColumn: Source_System

		annotation SummarizationSetBy = Automatic

	partition daysmart_contacts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\daysmart_contacts.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Full_Name", type text}, {"Email", type text}, {"Phone", type text}, {"Last_Appointment_Date", type date}, {"Primary_Service", type text}, {"Assigned_Staff", type text}, {"Total_Appointments", Int64.Type}, {"No_Shows", Int64.Type}, {"Total_Spent_USD", type number}, {"Loyalty_Points", Int64.Type}, {"SMS_Opt_In", type text}, {"Email_Opt_In", type text}, {"Next_Appointment_Date", type date}, {"Notes", type text}, {"Source_System", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

