table zoho_crm_contacts
	lineageTag: 2316ab7c-a459-4ebd-8eb9-9f7656adc345

	column Customer_ID
		dataType: string
		lineageTag: aeaf00e2-7356-4702-85a8-d9e45bf1162a
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Full_Name
		dataType: string
		lineageTag: 16bda736-c0c5-49c2-bcd0-274b92264aad
		summarizeBy: none
		sourceColumn: Full_Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: e379a796-3226-4729-8fd5-2dd82c6bf6f0
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 8edd5e0d-e0ff-4336-a0e7-168de569da7f
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Last_Appointment_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8df52d1d-fa36-496c-9f15-1ff90461c86a
		summarizeBy: none
		sourceColumn: Last_Appointment_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Lead_Status
		dataType: string
		lineageTag: e44abf29-80ae-4a86-81de-37f748c0d2ec
		summarizeBy: none
		sourceColumn: Lead_Status

		annotation SummarizationSetBy = Automatic

	column Account_Name
		dataType: string
		lineageTag: 303aeccb-c27e-4235-b3de-231fb8e2ec04
		summarizeBy: none
		sourceColumn: Account_Name

		annotation SummarizationSetBy = Automatic

	column Record_Owner
		dataType: string
		lineageTag: 0b940aa5-30b1-48c4-bc2a-72e06c4c39ae
		summarizeBy: none
		sourceColumn: Record_Owner

		annotation SummarizationSetBy = Automatic

	column Email_Opens
		dataType: int64
		formatString: 0
		lineageTag: 5604724c-72e4-4303-bbad-5578ec9587e4
		summarizeBy: sum
		sourceColumn: Email_Opens

		annotation SummarizationSetBy = Automatic

	column Email_Clicks
		dataType: int64
		formatString: 0
		lineageTag: ac674811-7bad-4c6d-9a1c-2e0c025e0fb3
		summarizeBy: sum
		sourceColumn: Email_Clicks

		annotation SummarizationSetBy = Automatic

	column Last_Activity_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 036d6777-b2a9-4e4e-b13c-c4bc701204b4
		summarizeBy: none
		sourceColumn: Last_Activity_Date

		variation Variation
			isDefault
			relationship: 66c57bd4-d39a-4129-b43f-79e3733fed4f
			defaultHierarchy: LocalDateTable_00362c5e-2474-4063-b439-ca04f1393bf5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Deal_Stage
		dataType: string
		lineageTag: 8324ef8a-8d10-45e2-86ad-31d3c13ecf92
		summarizeBy: none
		sourceColumn: Deal_Stage

		annotation SummarizationSetBy = Automatic

	column Annual_Revenue
		dataType: double
		lineageTag: 841ad1be-7d78-4f45-9a16-0d58928235ff
		summarizeBy: sum
		sourceColumn: Annual_Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tags
		dataType: string
		lineageTag: f66408cd-7ea9-4489-b964-d1ed9bf8660b
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column Source_System
		dataType: string
		lineageTag: d86b3716-c16c-4e42-888a-50ccb77155f3
		summarizeBy: none
		sourceColumn: Source_System

		annotation SummarizationSetBy = Automatic

	partition zoho_crm_contacts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\zoho_crm_contacts.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Full_Name", type text}, {"Email", type text}, {"Phone", type text}, {"Last_Appointment_Date", type date}, {"Lead_Status", type text}, {"Account_Name", type text}, {"Record_Owner", type text}, {"Email_Opens", Int64.Type}, {"Email_Clicks", Int64.Type}, {"Last_Activity_Date", type date}, {"Deal_Stage", type text}, {"Annual_Revenue", type number}, {"Tags", type text}, {"Source_System", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

