table zoho_crm_contacts
	lineageTag: 3ae81bb0-7141-4f16-9ff8-9ffd1a52daed

	column Customer_ID
		dataType: string
		lineageTag: 66433a0a-a8f5-42e7-a129-29b367e3ad98
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Full_Name
		dataType: string
		lineageTag: 96df747a-6111-4b86-83f7-6aa64e3d3691
		summarizeBy: none
		sourceColumn: Full_Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 3ab4bee6-e845-4d2c-8d3d-fa1150ac0822
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: ac3132e4-ea5c-41d7-99e9-50039343c43f
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Last_Appointment_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cbe3c245-82dd-4106-87e0-f14062abdd6f
		summarizeBy: none
		sourceColumn: Last_Appointment_Date

		variation Variation
			isDefault
			relationship: 01d385ac-e7e5-4716-9ee4-202ba28b55b5
			defaultHierarchy: LocalDateTable_0cffac4d-3505-4a69-b609-2005febddc46.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Lead_Status
		dataType: string
		lineageTag: b96764be-bdb0-4671-ae22-63101d294767
		summarizeBy: none
		sourceColumn: Lead_Status

		annotation SummarizationSetBy = Automatic

	column Account_Name
		dataType: string
		lineageTag: 86529880-6611-4f27-9307-63bee0f3b5ad
		summarizeBy: none
		sourceColumn: Account_Name

		annotation SummarizationSetBy = Automatic

	column Record_Owner
		dataType: string
		lineageTag: 10abb8f6-af7c-4757-973a-a7070e5d2b32
		summarizeBy: none
		sourceColumn: Record_Owner

		annotation SummarizationSetBy = Automatic

	column Email_Opens
		dataType: int64
		formatString: 0
		lineageTag: 61c989a2-c677-417c-9c2a-1c469cc84c90
		summarizeBy: sum
		sourceColumn: Email_Opens

		annotation SummarizationSetBy = Automatic

	column Email_Clicks
		dataType: int64
		formatString: 0
		lineageTag: 94d63609-b66b-472f-a8e5-90a72aa06ebd
		summarizeBy: sum
		sourceColumn: Email_Clicks

		annotation SummarizationSetBy = Automatic

	column Last_Activity_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd3c24a6-2f68-4059-820d-41a2083eaa47
		summarizeBy: none
		sourceColumn: Last_Activity_Date

		variation Variation
			isDefault
			relationship: 8cd8ee96-e142-47ae-a0a6-e2358adcbbf7
			defaultHierarchy: LocalDateTable_f33afdf2-be6c-4242-bd6e-4d0b519e4868.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Deal_Stage
		dataType: string
		lineageTag: 9a57a3a6-1795-4220-9d64-0cd5984cd371
		summarizeBy: none
		sourceColumn: Deal_Stage

		annotation SummarizationSetBy = Automatic

	column Annual_Revenue
		dataType: double
		lineageTag: a6084c4a-547a-4f71-8aee-c13e7817f468
		summarizeBy: sum
		sourceColumn: Annual_Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tags
		dataType: string
		lineageTag: 85a56567-be4b-4e68-9091-f35a8dbe5003
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column Source_System
		dataType: string
		lineageTag: 7dae00e6-76ab-498a-9b3a-ff96548b9527
		summarizeBy: none
		sourceColumn: Source_System

		annotation SummarizationSetBy = Automatic

	partition zoho_crm_contacts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Downloads\zoho_crm_contacts (1).csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Full_Name", type text}, {"Email", type text}, {"Phone", type text}, {"Last_Appointment_Date", type date}, {"Lead_Status", type text}, {"Account_Name", type text}, {"Record_Owner", type text}, {"Email_Opens", Int64.Type}, {"Email_Clicks", Int64.Type}, {"Last_Activity_Date", type date}, {"Deal_Stage", type text}, {"Annual_Revenue", type number}, {"Tags", type text}, {"Source_System", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

